### ISSUE TITLE
NA filtering

### ISSUE THREAD

**Issue by pkrog** [workflow4metabolomics/isa2w4m#1]
NA filtering does not to work.

**Comment by pkrog** [comment]
While running conversion of MTBLS2 with NA filtering on variable metadata column `database_identifier `:
```
Traceback (most recent call last):
  File "/Users/pierrick/dev/galaxy-isa/tools/isa2w4m/isa2w4m.py", line 9, in <module>
    isatab2w4m.main()
  File "/Users/pierrick/dev/isa-api/isatools/convert/isatab2w4m.py", line 574, in main
    filter_na_values(assays, table='var', cols=args_dict['var_na_filering'])
KeyError: 'var_na_filering'
```

**Comment by pkrog** [comment]
Corrected inside isatools library.
