### ISSUE TITLE
Error when converting MTBLS1 into Galaxy

### ISSUE THREAD

**Issue by pkrog** [workflow4metabolomics/isa2w4m#6]
```
Traceback (most recent call last):
  File "/Users/pierrick/Library/Python/3.6/lib/python/site-packages/pandas/core/indexes/base.py", line 2442, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5280)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5126)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20523)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20477)
KeyError: 'mass_to_charge'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pierrick/dev/galaxy-isa/tools/isa2w4m/isa2w4m.py", line 9, in <module>
    isatab2w4m.main()
  File "/Users/pierrick/dev/isa-api/isatools/convert/isatab2w4m.py", line 567, in main
    all_assays=args_dict['all_assays'])
  File "/Users/pierrick/dev/isa-api/isatools/convert/isatab2w4m.py", line 453, in convert2w4m
    variable_names = make_variable_names(measures_df)
  File "/Users/pierrick/dev/isa-api/isatools/convert/isatab2w4m.py", line 294, in make_variable_names
    for i, v in enumerate(assay_df[col].values):
  File "/Users/pierrick/Library/Python/3.6/lib/python/site-packages/pandas/core/frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "/Users/pierrick/Library/Python/3.6/lib/python/site-packages/pandas/core/frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "/Users/pierrick/Library/Python/3.6/lib/python/site-packages/pandas/core/generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "/Users/pierrick/Library/Python/3.6/lib/python/site-packages/pandas/core/internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "/Users/pierrick/Library/Python/3.6/lib/python/site-packages/pandas/core/indexes/base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5280)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5126)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20523)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20477)
KeyError: 'mass_to_charge'
```

**Comment by pkrog** [comment]
Corrected in isatools library. See [Adapt var names to NMR](https://github.com/pkrog/isa-api/commit/861d050fba2419cd1c61d80789fed5944690242f>).
